### ISSUE TITLE
Evaluator incompatible with phonopy/2.28.0

### ISSUE THREAD

**Issue by ebanyas** [Griffin-Group/DarkMAGIC#12]
The Calculator `evaluate()` method fails when using phonopy/2.28.0:

```
Traceback (most recent call last):
  File ".../calc_darkmagic_dailymod.py", line 53, in <module>
    run_calc(masses, times, material, light_scalar_mediator)
  File ".../calc_darkmagic_dailymod.py", line 25, in run_calc
    full_calc.evaluate(mpi=True)
  File ".../python3.12/site-packages/darkmagic/calculator.py", line 119, in evaluate
    max_bin_num = math.ceil(self.material.max_dE / self.numerics.bin_width)
                            ^^^^^^^^^^^^^^^^^^^^
  File ".../python3.12/site-packages/darkmagic/material.py", line 365, in max_dE
    self.phonopy_file.run_qpoints([[0, 0, 0]])
  File ".../python3.12/site-packages/phonopy/api_phonopy.py", line 2163, in run_qpoints
    raise RuntimeError(msg)
RuntimeError: Dynamical matrix has not yet built.
```

Downgrading to phonopy/2.21.0 resolves the issue.

**Comment by oashour** [comment]
The bug was upstream in `phonopy` itself-- their YAML parser broke and stopped reading the force constants. This was resolved in 2.33.0.
